Repository dmarro89/dare-db, pull requests merged in 2024-06, with the labels that each got.

#18 10 implement configuration and basic logging
  .gitignore
  go.mod
  go.sum
  logger/formatter.go
  logger/logger.go
  main.go
  server/configuration.go
  server/configuration_test.go
  server/constants.go
  server/dare-server.go
  server/factory.go
  server/factory_test.go
  server/server.go
  server/server_test.go
  utils/utils.go
Labels: enhancement, feature

#29 Add documentation for contributors
  .github/pull_request_template.md
  README.md
Labels: documentation

#27 Creating DareLogger struct, restructuring logger and configuration struct
  logger/logger.go
  server/configuration.go
  server/configuration_test.go
  server/server.go
  server/server_test.go
Labels: enhancement
